[package]
name = "shiloh-audio"
description = "Spatial audio and mixing for Shiloh3D (Rust-first)"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true

[dependencies]
glam.workspace = true
parking_lot.workspace = true
shiloh-core = { workspace = true }
tracing.workspace = true

[lints]
workspace = true
